----Engine Assets

Assets = {
"Textures/lowestTile.tga",
"Textures/lowTile.tga",
"Textures/highTile.tga",
"Textures/highestTile.tga",
"Textures/detailmap.tga",
"Textures/heightmap.bmp",
"Models/Ogro/Tris.md2",
"Models/Ogro/Ogrobase.pcx",
"Models/berserk/tris.md2",
"Models/berserk/skin.pcx",
"Models/soldier/tris.md2",
"Models/soldier/skin.pcx",
"Models/mutant/tris.md2",
"Models/mutant/skin.pcx",
"Models/house1/house1.obj",
"Models/bananaTree/bananaTree.obj",
"Models/tree1/tree1.obj",
"Models/ruralStall/ruralStall.obj",
"Models/chapel/chapel.obj",
"Models/church/church.obj",
"Models/number_1/number_1.obj",
"Models/number_2/number_2.obj",
"Models/number_3/number_3.obj",
"Models/number_4/number_4.obj",
"Models/number_5/number_5.obj",
"Textures/menu.bmp",
"Textures/exitScreen.bmp"
}